/**
 * isKoreanCoordinates Property-Based Tests
 *
 * Feature: navigation-google-maps-default
 * Property 1: Boundary classification biconditional
 *
 * Validates: Requirements 1.2, 1.3, 4.4
 */
import * as fc from 'fast-check'
import { isKoreanCoordinates, generateDirectionsUrls } from '@/lib/directions'

const KOREA_LAT_MIN = 33.0
const KOREA_LAT_MAX = 38.7
const KOREA_LNG_MIN = 124.5
const KOREA_LNG_MAX = 132.0

describe('Feature: navigation-google-maps-default', () => {
  describe('Property 1: Boundary classification biconditional', () => {
    /**
     * **Validates: Requirements 1.2, 1.3, 4.4**
     *
     * For any coordinate pair (lat, lng), isKoreanCoordinates(lat, lng)
     * returns true iff 33.0 <= lat <= 38.7 AND 124.5 <= lng <= 132.0
     */
    it('should return true iff coordinates are within Korea boundary', () => {
      fc.assert(
        fc.property(
          fc.double({
            min: -90,
            max: 90,
            noNaN: true,
            noDefaultInfinity: true,
          }),
          fc.double({
            min: -180,
            max: 180,
            noNaN: true,
            noDefaultInfinity: true,
          }),
          (lat, lng) => {
            const result = isKoreanCoordinates(lat, lng)
            const expected =
              lat >= KOREA_LAT_MIN &&
              lat <= KOREA_LAT_MAX &&
              lng >= KOREA_LNG_MIN &&
              lng <= KOREA_LNG_MAX

            return result === expected
          }
        ),
        { numRuns: 100 }
      )
    })
  })

  describe('Edge cases: 도서 지역 및 인접 해외 좌표', () => {
    /**
     * **Validates: Requirements 4.1, 4.2, 4.3**
     *
     * 바운딩 박스 방식의 한계로 인해 후쿠오카/쓰시마는
     * 경계 범위 내에 포함되어 국내로 분류됨 (known limitation)
     */

    it('제주도 (33.4, 126.5) → 국내 분류', () => {
      expect(isKoreanCoordinates(33.4, 126.5)).toBe(true)
    })

    it('울릉도 (37.5, 130.9) → 국내 분류', () => {
      expect(isKoreanCoordinates(37.5, 130.9)).toBe(true)
    })

    it('후쿠오카 (33.6, 130.4) → 바운딩 박스 내 포함 (국내 분류)', () => {
      // 지리적으로는 해외이나, 바운딩 박스 범위 내에 포함됨
      expect(isKoreanCoordinates(33.6, 130.4)).toBe(true)
    })

    it('쓰시마 (34.4, 129.3) → 바운딩 박스 내 포함 (국내 분류)', () => {
      // 지리적으로는 해외이나, 바운딩 박스 범위 내에 포함됨
      expect(isKoreanCoordinates(34.4, 129.3)).toBe(true)
    })
  })

  describe('Property 2: Google Maps URL contains coordinates', () => {
    /**
     * **Validates: Requirements 2.2**
     *
     * For any valid coordinate pair (lat, lng) and destination name,
     * the Google Maps URL generated by generateDirectionsUrls SHALL
     * contain the lat and lng values in the URL string.
     */
    it('should include lat and lng in Google Maps URL', () => {
      fc.assert(
        fc.property(
          fc.double({
            min: -90,
            max: 90,
            noNaN: true,
            noDefaultInfinity: true,
          }),
          fc.double({
            min: -180,
            max: 180,
            noNaN: true,
            noDefaultInfinity: true,
          }),
          fc.string(),
          (lat, lng, name) => {
            const urls = generateDirectionsUrls({
              destination: { lat, lng },
              destinationName: name,
            })

            return (
              urls.google.includes(String(lat)) &&
              urls.google.includes(String(lng))
            )
          }
        ),
        { numRuns: 100 }
      )
    })
  })
})
